### ISSUE TITLE
Link to build log leads to 404

### ISSUE THREAD

**Issue by andy5995** [TheAssassin/pyuploadtool#5]
On Releases->Continuous, the link to the build log leads to a 404 error page.

I noticed it first when trying out pyuploadtool on [one of my small projects](https://github.com/theimpossibleastronaut/aa-pokerhands/releases), and also on the pyuploadtool project repo.

**Comment by TheAssassin** [comment]
Instead of https://github.com/theimpossibleastronaut/aa-pokerhands/runs/981622730, it should be https://github.com/theimpossibleastronaut/aa-pokerhands/actions/runs/981622730, I guess.
